"""
Find byte-identical images shared between splits and write exclusion lists.

Policy (keeps TEST untouched so results stay comparable to published work):
    - val   : drop anything also in test or train
    - train : drop anything also in test
Files are never deleted; dataset.py skips the listed paths.

Usage (from the repo root):
    python src/make_excludes.py --script bengali
"""

import argparse
import hashlib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src.common import SPLITS, exclude_path, gt_path, load_cfg, read_gt  # noqa: E402


def hash_split(cfg, script, split):
    """Return {md5: [relative_paths]} for every image in the annotation.
    A list, so within-split duplicates are all excluded, not just the first."""
    gt = gt_path(cfg, script, split)
    out, n = {}, 0
    for rel, _ in read_gt(gt, cfg["shared"]["unicode_norm"]):
        h = hashlib.md5((gt.parent / rel).read_bytes()).hexdigest()
        out.setdefault(h, []).append(rel)
        n += 1
    if n != len(out):
        print(f"  note: {n - len(out)} within-split duplicate images (kept, not excluded)")
    return out


def main(script, cfg):
    H = {}
    for s in SPLITS:
        print(f"hashing {s} ...", flush=True)
        H[s] = hash_split(cfg, script, s)
        print(f"  {sum(len(x) for x in H[s].values())} images, {len(H[s])} unique")

    t, v, te = set(H["train"]), set(H["val"]), set(H["test"])
    print(f"\noverlap  train&val={len(t & v)}  train&test={len(t & te)}  val&test={len(v & te)}")

    plan = {
        "val":   (v & te) | (v & t),
        "train": t & te,
    }
    for split, hashes in plan.items():
        p = exclude_path(cfg, script, split)
        p.parent.mkdir(parents=True, exist_ok=True)
        paths = sorted(r for h in hashes for r in H[split][h])
        header = (f"# {script} {split}: images byte-identical to another split.\n"
                  f"# Generated by src/make_excludes.py. {len(paths)} entries.\n")
        p.write_text(header + "\n".join(paths) + ("\n" if paths else ""), encoding="utf-8")
        kept = sum(len(v) for v in H[split].values()) - len(paths)
        print(f"{split:5s}: excluding {len(paths):6d}, keeping {kept:6d}  -> {p.name}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--script", required=True, choices=["bengali", "kannada"])
    ap.add_argument("--config", default="config.yaml")
    a = ap.parse_args()
    main(a.script, load_cfg(a.config))
